Desenvolvimento de modal de requerimentos
O-Povo-Requer/opr-front pull request #15
Opened 2022-03-11 01:09 UTC by JosiasBatista

2022-03-11 15:30 UTC, franklingg requested changes
Ficou interessante, mas trouxe alguns comentários para melhorar mais o componente.

2022-03-11 15:30 UTC, franklingg commented on src/components/Modal/index.js
> +    }, [ref]);
`useImperativeHandle` já é feito para trabalhar com refs, a dependência no hook não é necessária. Segundo o lint:
"React Hook useImperativeHandle has an unnecessary dependency: 'ref'. Either exclude it or remove the dependency array"
```suggestion
    }, []);
```

2022-03-11 15:30 UTC, franklingg commented on src/components/Requirement/index.js
> +            </Modal>
Ao ver o nome da PR "Desenvolvimento de modal de requerimentos" deu a entender que a tarefa seria fazer a modal em si, mas vi que esta é outra tarefa. Então acredito que seria melhor que fosse "Desenvolvimento de card de requerimento"

2022-03-11 15:30 UTC, franklingg commented on src/components/Modal/index.js
> +    console.log(modalStatus)
Acredito que seja um log feito durante o desenvolvimento, seria bom retirá-lo.

2022-03-11 15:30 UTC, franklingg commented on src/components/Requirement/index.js
> +        console.log(requirement)
Acredito que seja um log feito durante o desenvolvimento, seria bom retirá-lo.

2022-03-11 15:30 UTC, franklingg commented on src/components/Requirement/index.js
> +                    <span>{getDateFormated()}</span>
Essa função é usada somente nesse momento no componente, acredito que não seja necessária e poderia ser usada diretamente.
```suggestion
                    <span>{moment.unix(requirement.creationDate).format("DD/MM/YYYY")}</span>
```

2022-03-11 15:30 UTC, franklingg commented on src/components/Requirement/styles.css
> +.requirement_container {
Essa foi a forma que o componente se apresentou na minha tela:
![image](https://user-images.githubusercontent.com/61962950/157896021-a0ad62e6-89ba-45a8-b997-184ace68fffa.png)

E esse é o componente no figma:
![image](https://user-images.githubusercontent.com/61962950/157896194-4aebe7bd-d061-46f8-af33-918d5ecdaca5.png)


Quanto ao estilo no geral, algumas observações comparando ao figma:

- Status e o texto em si (usuário e descrição do requerimento) desalinhados;
- Imagem do perfil muito longe do nome/localidade;
- Localidade muito pequena comparada ao nome (apesar de que, pessoalmente, acho muito melhor e poderia ser editado no figma para ficar assim);
- font-weight de textos não-negritos deve ser 500;
- Texto da descrição do requerimento deve ser justificado;
- Container do requerimento deve ter box-shadow.

2022-03-12 02:50 UTC, JosiasBatista commented
Removi os logs e ajustei os pontos com os métodos! A questão do layout tinha algumas coisas diferentes mesmo e eu ajustei, mas as partes do box-shadow não tem, esqueci de remover só dessa tela no figma, vou tirar. font-weight 500 não gera diferença nenhuma nos textos (to usando em alguns um opacity para diferenciação como na data, mas ficou muito claro mesmo eu diminui o opactity, ve o que vc acha por favor). A localidade eu deixei menor mesmo, atulizei no figma. A questão dos status vou confirmar com o pessoal do backend pq tinha sido uma conversa informal que ficaria um booleano, mas vou me certificar e caso va ficar com os 3 status ou so com dois atualizo ou no figma ou no front.

2022-03-12 03:02 UTC, franklingg commented
Você commitou, @JosiasBatista ? Aqui só tem um commit que foi a correção do _ref_

2022-03-12 03:37 UTC, JosiasBatista commented
Commitei sim! Foi o commit com o nome "[adjusting required modifications]". Inclusive fiz mais umas modificações agora! Adicionei uns requerimentos em uma tela para visualizar melhor:
![image](https://user-images.githubusercontent.com/55117241/158002258-aee7d197-113b-4ad3-95ac-6ce12a88538f.png)

2022-03-12 13:58 UTC, franklingg requested changes
Tudo ótimo, só um último detalhe.

2022-03-12 13:58 UTC, franklingg commented on src/components/Modal/index.js
> +    console.log(modalStatus)
Só faltou resolver este console.log, de resto tá tudo ótimo!

2022-03-12 20:24 UTC, JosiasBatista commented on src/components/Modal/index.js
> +    console.log(modalStatus)
Eita, jurava que havia removido! Foi remover e colocar para possibilitar os 3 status como sendo "concluded", "not_accepted" e "analisys". O back vai deixar o status como string então conseguimos definir um padrão de status.

2022-03-12 23:10 UTC, franklingg approved these changes
Tudo certo!

2022-03-12 23:17 UTC, merged