Feat/modal requirements
O-Povo-Requer/opr-front pull request #17
Opened 2022-03-11 15:35 UTC by MatheusHG

# Modal for viewing and editing requirements

<img src="https://user-images.githubusercontent.com/56003521/157897620-673404a9-51c6-445f-a26d-d7e87e515a25.gif" />

2022-03-11 17:42 UTC, ielepassos approved these changes

2022-03-11 23:53 UTC, franklingg requested changes
Descrevi alguns ajustes que julguei importantes pra task.

2022-03-11 23:53 UTC, franklingg commented on src/components/ModalViewRequeriments/index.js
> +      <Modal ref={modalRefLegislador} additionalClass="legislador">
A escolha de legislador deve ser com dois _dropdown_: um para o estado, e o segundo para o nome do legislador. Ao selecionar, as informações do legislador devem aparecer abaixo, de forma não-editável.

2022-03-11 23:53 UTC, franklingg commented on src/components/ModalViewRequeriments/styles.css
> +.box {
Ao abrir o componente, ele se apresentou assim na minha tela:
![image](https://user-images.githubusercontent.com/61962950/157986298-1ffa47cb-c474-4b29-ae33-1d1141829cc5.png)

Considerações sobre o estilo (ver imagem acima):
- O container fica em estado _focused_ ao abrir, com uma borda preta;
- O conteúdo me parece muito próximo da borda do container, seria melhor aumentar o _padding_ de 20px para 30px;
- Ao mudar para o modo de edição, o título deveria ser "Modificação de Requerimento";
- Data do ocorrido precisa de um espaçamento entre o título e a data em si;
- Lista de mídias muito próximas dos apoios, a margem deve ser maior entre eles;
- "Lista mídias" -> "Lista de mídias"
- Conteúdo do comentário muito próximo do avatar/nome do perfil;
- Submissão do comentário não funciona (por enquanto pode submeter como um usuário qualquer e que só existe em _runtime_)
- Como o container tem bordas circulares, acredito que ficaria mais interessante uma [scrollbar estilizada](https://www.w3schools.com/howto/howto_css_custom_scrollbar.asp), você pode estilizar para deixá-la mais sutil, como a do figma por exemplo:
![image](https://user-images.githubusercontent.com/61962950/157987729-99da4c05-18da-4395-976f-f1844f5c49e1.png)

2022-03-11 23:53 UTC, franklingg commented on src/components/ModalViewRequeriments/index.js
> +                <Button key={id}>
Já que é um botão, deveria ter alguma ação ao clicar na imagem (expandir seria o ideal). Isso poderia ser feito com uma modal que teria essa imagem (com background transparente)

2022-03-11 23:53 UTC, franklingg commented on src/components/ModalViewRequeriments/index.js
> +              <input placeholder="Digite sua mensagem..." type="text" />
Também deve existir um `keyListener` para o teclado, para que o comentário seja submetido se o usuário apertar _Enter_.

2022-03-11 23:53 UTC, franklingg commented on src/components/ModalViewRequeriments/index.js
> +                      <span>{item.party}</span>
Acredito que também seria ideal ter o estado e/ou cidade do legislador, além avatar do legislador (este último mais opcional do que os outros). Você pode falar com o pessoal de prototipagem para incluírem isso

2022-03-11 23:53 UTC, franklingg commented on src/components/ModalViewRequeriments/index.js
> +                <DeleteOutlineIcon />
Ao invés de uma lixeira, acredito que um botão de "x" seja mais adequado. Exemplo do github:
![image](https://user-images.githubusercontent.com/61962950/157987905-2da16d11-2610-4843-af3a-8efb24fad6a2.png)

2022-03-11 23:53 UTC, franklingg commented on src/components/ModalViewRequeriments/index.js
> +                <Button key={id}>
No modo de edição, a imagem deve ser editável (substituir ou deletar). E deveria ter um botão de adicionar imagens.

2022-03-11 23:53 UTC, franklingg commented on src/components/ModalViewRequeriments/index.js
> +                <Button onClick={() => editLegislador()} className="settings-new">Adicionar mais</Button>
O botão de adicionar legisladores deve ficar no carousel, como no figma:
![image](https://user-images.githubusercontent.com/61962950/157988374-5e37cf5f-1b87-403b-b27e-1a8b0d867bb5.png)

2022-03-11 23:53 UTC, franklingg commented on src/components/ModalViewRequeriments/index.js
> +            <SettingsOutlinedIcon color="action" />
Você pode conversar isso com o pessoal de prototipagem, mas acredito que com outro ícone com um texto fique bem mais claro que a engrenagem. Por exemplo:
![image](https://user-images.githubusercontent.com/61962950/157989591-30334252-440e-4638-8acb-25635ac4c566.png)
E no modo edição algo como:
![image](https://user-images.githubusercontent.com/61962950/157989885-c7332af0-bf15-4c53-b12f-7eb7bb32c406.png)

2022-03-11 23:53 UTC, franklingg commented on src/components/ModalViewRequeriments/index.js
> +          <TextField
Isso teria que ser visto, mas acredito ser mais adequado que as Tags sejam pré-definidas, então seria um _dropdown_ para o usuário escolher uma das tags do sistema. Isso evita que tags sem relação com o sistema possam ser criadas.

2022-03-13 00:05 UTC, JosiasBatista commented
Tem um ponto também que percebi que da forma que ficou no layout no figma deixou aberto a interpretações. Mas a parte "Requerimento do Usuário Marcos Antônio" no layout seria o título do requerimento.

2022-03-14 21:47 UTC, MatheusHG reviewed
Punctual adjustments

2022-03-14 22:54 UTC, merged

2022-03-14 23:44 UTC, franklingg reviewed
Pontos a serem checados:

- A branch precisa ser integrada com `dev`, está muitos commits atrás.
- Deixar o componente principal (`ModalViewAndEditRequirements`) no inicio, antes dos outros subcomponentes. 
- O nome do componente também está muito grande, só `ModalRequirements` é suficiente (só teremos ele e o de novo requerimento).
- A questão dos ícones de editar/salvar não foi resolvida
- Clicar fora da modal da imagem expandida não a fecha.

2022-03-14 23:44 UTC, franklingg commented on src/components/ModalViewAndEditRequirements/index.js
> +  const salveDate = (e) => {
Mais uma vez a questão do inglês

```
const saveDate = (e) => {
```

2022-03-14 23:44 UTC, franklingg commented on src/components/ModalViewAndEditRequirements/index.js
> +  const [message, setMessage] = useState(requirement.message);
essas variáveis também são acessíveis pelo state requeriment

2022-03-14 23:44 UTC, franklingg commented on src/components/ModalViewAndEditRequirements/index.js
> +  );
essas variáveis também são acessíveis pelo state requeriment

2022-03-14 23:44 UTC, franklingg commented on src/components/ModalViewAndEditRequirements/Response.json
> +{
Esse arquivo não é mais necessário porque em dev já temos os mocks em `service/api.js`

2022-03-15 00:24 UTC, MatheusHG commented on src/components/ModalViewAndEditRequirements/index.js
> +  const [message, setMessage] = useState(requirement.message);
O "message" precisa ser um estado, pois ele recebe valores do input