feat: add service api and mock for the models of the system.
O-Povo-Requer/opr-front pull request #25
Opened 2022-03-12 23:27 UTC by franklingg

Adiciona axios para integração com o backend e mocks de usuário, legislador e requerimento.
Para acessar a api, é necessário setar a url do backend criando o arquivo `.env` como no `.env.example`

2022-03-12 23:47 UTC, JosiasBatista commented
Achei interessante a estrutura de Mocks. Eu estava pensando em utilizar um MiracleJS para conseguir simular o mais real possível chamadas ao backend, mas acredito que no curto tempo fique um pouco mais complicado a implementação. Depois a gente tenta já adicionar o JWT no header também pq vai precisar passar em todas as chamadas mesmo.

2022-03-13 00:08 UTC, JosiasBatista requested changes
Tudo perfeito. Só estou requisitando mudança pq no mock do requerimento precisa adicionar também o título do requerimento. A parte de adicionar valores default de header no axios a gente pode fazer posteriorment quando estiver mais avançado no estágio de integração.

2022-03-13 00:53 UTC, franklingg commented
Adicionei o título e a versão autenticada da API. Como terão rotas que não precisarão de autenticação, acredito que fique melhor deixar as duas instâncias da API (com e sem auth). O token já é lido automaticamente do `localStorage`

2022-03-13 01:18 UTC, JosiasBatista approved these changes
Por mim tudo okay! Essa semana vou adicionando as tasks de integração para a gente começar a adiantar esse ponto.

2022-03-13 01:34 UTC, merged