User home page
O-Povo-Requer/opr-front pull request #26
Opened 2022-03-14 03:26 UTC by JosiasBatista

Posteriormente será feita a renderização da página home para o usuário normal ou para o legislador diferenciando entre os dois componentes.

2022-03-14 14:07 UTC, franklingg requested changes
A branch está desatualizada da `dev`. O arquivo `requerimentsJsonMock.json` pode ficar dentro de `service/api.js` com os outros mocks, algo como `mockListRequeriments`. Nesse primeiro momento, o search poderia sempre retornar uma lista vazia (independente do _keyword_), dessa forma essa tela já poderia ser implementada:
![image](https://user-images.githubusercontent.com/61962950/158189032-427c5ba2-09f7-4360-b223-44c3441aa33a.png)

2022-03-14 22:41 UTC, JosiasBatista commented
Nossa, verdade! Eu tinha começado o desenvolvimento antes da estrutura, vou ajustar esse ponto e a ideia da pesquisa vazia no momento foi muito boa. Vou tentar ajustar hoje ainda.

2022-03-15 00:27 UTC, RicardoGFelix reviewed
Boa noite, Josias! Acredito que a solução está correta, no entanto seu PR possui conflitos que provavelmente se dão pelo que Franklin comentou e precisam ser solucionados antes de realizar o merge.

2022-03-15 02:19 UTC, JosiasBatista commented
Correções feitas! A página de listagem de requerimentos atualmente está sem o ícone do Figma pois não achei na lib que estamos usando do Material UI. Podemos buscar outro ícone posteriormente.

2022-03-15 22:14 UTC, RicardoGFelix approved these changes
Boa, Josias! Tudo certo, man!

2022-03-15 22:15 UTC, franklingg approved these changes
Também me parece tudo ok, o ícone de nenhum encontrado você poderia usar como um <img> mesmo, pegando o do figma.

2022-03-15 22:16 UTC, merged