Citizen and Legislator registration
O-Povo-Requer/opr-front pull request #35
Opened 2022-03-19 03:09 UTC by JosiasBatista

2022-03-20 00:17 UTC, franklingg requested changes
Ficou muito bom, mas ainda precisa de ajustes

2022-03-20 00:17 UTC, franklingg commented on src/pages/Register/index.js
> +            }
Já que existe a função de validateCpf, a checagem de length pode ficar por conta dessa função.
```suggestion
            if (!!name && !!state && !!city && !!email && !!password && !!passwordConfirmation) {
                let isValid = true;
                isValid = validateEmail(email) && validateCPF(cpf) && (password === passwordConfirmation);

                setIsFormCompleted(isValid);
            } else {
                setIsFormCompleted(false);
            }
```

2022-03-20 00:17 UTC, franklingg commented on src/service/citizen.service.js
> +    console.log(citizenData)
Remover log

2022-03-20 00:17 UTC, franklingg commented on src/service/citizen.service.js
> +}
Existe alguma situação no sistema em que o usuário poderia ser deletado? Se não, não acho que seja uma boa deixar essa função disponível.

2022-03-20 00:17 UTC, franklingg commented on src/service/citizen.service.js
> +}
Essa é uma rota autenticada.
```suggestion
export async function updateCitizen(updateData) {
    return apiAuth.put("/cidadao", updateData);
}
```

2022-03-20 00:17 UTC, franklingg commented on src/service/citizen.service.js
> +import { api } from "./api";
As funções de `citizen.service.js` e `legislator.service.js`, além de invocarem a API, devem salvar o usuário logado no state do redux, para ficarem disponíveis nas outras partes do sistema.
Já existem as actions de SAVE_USER e UPDATE_USER

2022-03-20 00:17 UTC, franklingg commented on src/service/citizen.service.js
> +            if (response.data) {
A rota POST /cidadao está retornando esse objeto, o token não é feito no cadastro.
![image](https://user-images.githubusercontent.com/61962950/159142719-4c858f75-da3f-4271-970c-f8c5b2b83ff3.png)

2022-03-20 15:58 UTC, ielepassos reviewed
Concordo com tudo citado por @franklingg 
No mais, ficou muito bom!!

2022-03-20 23:52 UTC, JosiasBatista commented on src/pages/Register/index.js
> +            }
Concordo plenamente com esse ponto. Vou ajustar hoje!

2022-03-20 23:54 UTC, JosiasBatista commented on src/service/citizen.service.js
> +}
Realmente não há no momento! Vou remover, mas acho que seria bom implementar futuramente essa possibilidade. Dependendo caso a gente decida levar o projeto para a frente normalmente em políticas de privacidade de dados é exigido que tenha a possibilidade. Mas vou remover por enquanto

2022-03-20 23:55 UTC, JosiasBatista commented on src/service/citizen.service.js
> +import { api } from "./api";
Não tinha visto que as actions já tinha sido criadas. Vou fazer merge de dev para essa branch e utilizar. Valeu

2022-03-20 23:56 UTC, JosiasBatista commented on src/service/citizen.service.js
> +            if (response.data) {
Vish... não tinha visto isso. Vamos ter que adicionar um passo então de pelo menos colocar um "alert" para informar que o cadastro ocorreu corretamente ou não e depois redirecionar o cliente para o login. Acho que vou utilizar só um alert mesmo para não complicar as coisas, oq acha?

2022-03-21 00:32 UTC, franklingg commented on src/service/citizen.service.js
> +            if (response.data) {
Sim, acredito que seja o ideal por enquanto

2022-03-21 23:38 UTC, JosiasBatista commented
Fiz as correções! O cadastro vai estar funcionando, mas o login provavelmente não vai dar certo por conta dos ajustes de criptografia para validação que precisam ser feitos no back.

2022-03-22 03:28 UTC, franklingg requested changes
Me parece tudo certo, mas tem um problema que precisamos verificar

2022-03-22 03:28 UTC, franklingg commented on src/service/citizen.service.js
> +                    saveUser(userInformations);
saveUser é uma função pura, ela só gera a action de salvar mas a action precisa ser despachada para a store. Isso pode ser feito importando a store dentro de citizen.service (de "../store") e chamando `store.dispatch(saveUser(data))`, ou invocando a dispatch dentro do componente (com `useDispatch`) e passando o dispatch para a função `registerCitizen`.
Eu testei as duas formas e, apesar de atualizar na store, o usuário não é resgatado quando se chama no useSelector, mas talvez eu só não manje bem de redux kkk você pode o que sai, e se ficar muito complicado podemos só salvar o id do usuário no localStorage e invocar um GET /usuario quando necessário (infelizmente).

2022-03-23 02:30 UTC, JosiasBatista commented on src/service/citizen.service.js
> +                    saveUser(userInformations);
Ja tive uma vez o problema de atualizar na store mas o usuário ser mantido o default que havia sido armazenado. Se não me engano isso pode acontece quando mais de uma instância do redux é criada dentro da aplicação. Vou tentar analisar aqui

2022-03-24 02:33 UTC, franklingg approved these changes
Show!

2022-03-24 03:16 UTC, merged