change login + add initial logic
O-Povo-Requer/opr-front pull request #41
Opened 2022-03-21 17:04 UTC by ielepassos

- modifica o login para que seja feito com o cpf
- adiciona states iniciais
- adiciona logica para que o login seja feito clicando no enter também, além do botão
- filtrei o cpf para que recebamos ele sem os caracteres, mas acredito que dê pra ser feito com regex também

2022-03-22 23:43 UTC, MatheusHG requested changes

2022-03-22 23:43 UTC, MatheusHG commented on src/pages/Login/index.js
> +  useEffect(() => {
```suggestion
```
Não precisa de utilizar isso. Envolver todo o campo do formulário no HTML utilizando a Tag form, já resolve todo esse código.
``` 
<form onSubmit={handleLogin}>
...
</form>
```
onde os "..." seria os inputs e o botão de "Login" do tipo "submit"

2022-03-22 23:43 UTC, MatheusHG commented on src/pages/Login/index.js
> +          <input
```suggestion
```
Você pode usar o [react-input-mask](https://blog.logrocket.com/implementing-react-input-mask-web-apps/) para formatar a entrada do CPF, é simples e fácil. Um ponto positivo é que irá formatar automaticamente quando o usuário estiver digitando e só irá aceitar números. 

Ficaria assim:
```
<InputMask
      placeholder="CPF"
      className="login_input"
      maskPlaceholder=" "
      mask='999.999.999-99' 
      value={login}
      onChange={(e) => setLogin(e.target.value)} 
      required
/>

2022-03-22 23:43 UTC, MatheusHG commented on src/pages/Login/index.js
> +            onChange={(e) => setPassword(e.target.value)}
```suggestion
            onChange={(e) => setPassword(e.target.value)}
            required
```

Campo obrigatório

2022-03-23 01:41 UTC, ielepassos commented
Qual a versão do react-router-dom que vocês estão usando? 
Pq da na v5.2.0 ( e semelhantes) o useNavigate não está disponível, e na 6 o use history não está disponível.
Pelo que entendi, um substitui o outro, mas no nosso código temos os dois e, pelo menos por aqui, desse jeito está quebrando.

2022-03-24 00:48 UTC, ielepassos commented
Acredito que, agora, todas as mudanças solicitadas foram feitas :)

2022-03-24 01:30 UTC, ielepassos commented
O título do form foi tirado intencionalmente? se não, posso colocar aqui novamente

2022-03-24 23:25 UTC, JosiasBatista commented
Assim que o back ajustar a rota de buscar usuário vou fazer um teste para ver se está funcionando e a gente fecha esse PR

2022-03-25 23:41 UTC, merged