Feat/list requirements
O-Povo-Requer/opr-front pull request #45
Opened 2022-03-23 22:44 UTC by RicardoGFelix

Tela de listagem de requerimentos ainda não funcional criada.

2022-03-24 20:00 UTC, matheusforlan commented
A página inicial tem conflitos com a branch e o mockRequirment não está sendo mais utilizado, é preciso fazer uma transição de como os dados estão sendo pegos.

2022-03-24 21:54 UTC, matheusforlan requested changes
A página inicial tem conflitos com a branch e o mockRequirement não está sendo mais utilizado, é preciso fazer uma transição de como os dados estão sendo pegos.

2022-03-24 22:50 UTC, JosiasBatista commented
Verdade, os pontos que Forlán citou precisam ser ajustados. Faz um merge de dev para essa branch, nesse momento estamos utilizando context API do react.

2022-03-25 00:55 UTC, RicardoGFelix commented
Ajustes solicitados devidamente realizados, pessoal.

2022-03-25 01:10 UTC, matheusforlan approved these changes

2022-03-25 01:10 UTC, matheusforlan commented
Acredito que agora está tudo ok.

2022-03-25 01:38 UTC, JosiasBatista approved these changes

2022-03-25 01:39 UTC, merged