update user funcionality
O-Povo-Requer/opr-front pull request #49
Opened 2022-03-24 19:59 UTC by matheusforlan

2022-03-24 23:32 UTC, JosiasBatista requested changes
Ta bom o desenvolvimento e a estrutura, mas tem dois pontos que precisa mudar. Antes de fazer a atualização a gente precisa identificar se o usuário é um cidadão ou legislador. E o mais adequado para atualizar o usuário no context é utilizar o método "updateUser"

2022-03-25 00:47 UTC, matheusforlan commented
sim, faz sentido. na minha cabeça só o usuário poderia mudar seus dados, vou rever isso.

2022-03-25 14:40 UTC, matheusforlan commented
acredito que agora esteja ok.

2022-03-25 23:21 UTC, ielepassos approved these changes

2022-03-26 00:28 UTC, merged